version: "3.7"
services:
  odoo_app:
    image: odoo:18.0

    volumes:
      - odoo_app_data:/var/lib/odoo
      - odoo_app_config:/etc/odoo
      - odoo_app_addons:/mnt/extra-addons

    networks:
      - {{network_name}}

    environment:
      ## Postgres
      - HOST=postgres
      - USER=odoo
      - PASSWORD={{postgres_password}}

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.odoo_app.rule=Host(`{{odoo_url}}`)
        - traefik.http.routers.odoo_app.entrypoints=websecure
        - traefik.http.routers.odoo_app.tls=true
        - traefik.http.routers.odoo_app.service=odoo_app
        - traefik.http.routers.odoo_app.tls.certresolver=letsencryptresolver
        - traefik.http.services.odoo_app.loadbalancer.server.port=8069

volumes:
  odoo_app_data:
    external: true
    name: odoo_app_data
  odoo_app_config:
    external: true
    name: odoo_app_config
  odoo_app_addons:
    external: true
    name: odoo_app_addons

networks:
  {{network_name}}:
    external: true
    attachable: true
    name: {{network_name}}
